version: '3'

services:
    python:
        build:
            context: .
            dockerfile: dockerfile
        # restart: always
        container_name: test-python
        volumes:
            - ./app:/app
        ports:
            - "8001:80"
        stdin_open: true
        tty: true      
